import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "WikiUncle App",
  description: "Generated by reniuszka",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-green-950 text-white">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
